name: apps

services:
  db:
    image: postgres:16.0
    volumes:
      - db-volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sqluser
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

volumes:
  db-volume:
  cache-volume:
